feat(i18n): italian localization
phyver/GameShell pull request #87
Opened 2022-05-27 09:11 UTC by Mte90

So we are starting to localize it in italian!

If you want to help reach me or contribute to my repo so we can review our localization each other!
Se vuoi contribuire contattami o contribuisci al mio repo cosí possiamo revisionarci a vicenda!
![Screenshot_20220527_113804](https://user-images.githubusercontent.com/403283/170674049-a67ef259-7141-474a-b23e-a05be18e7210.png)
Se hai notato errori nello screen ho giá sistemato...

Docs about localization: https://github.com/phyver/GameShell/blob/master/doc/i18n.md

**The missions requires your help to be localized!**

**Per la revisione facciamola alla fine, prima traduciamo tutto cosí si fa prima**

This PR is a WIP.

2022-05-27 14:21 UTC, serhack requested changes

2022-05-27 14:21 UTC, serhack commented on README-it.md
> +Insegnare a studenti universatari o delle superiori a usare un terminale Unix non é la cosa piú semplice o divertente. Gameshell é stato creato come strumento per aiutare gli studenti alla [Universit
> per fare pratica con un terminale *reale* per imparare divertendosi.

Forse è meglio: "per fare pratica con un terminale *reale* e imparare divertendosi."

2022-05-27 14:21 UTC, serhack commented on README-it.md
> +L'idea originale, di  Rodolphe Lepigre, era di avere una sessione bash standard con una configurazione specifica via file definiti "missioni" che potevano essere "verificate" tramite i progressi nel
> di  Rodolphe Lepigre

Doppio spazio

> bash

Forse è meglio "shell"?

> L'idea originale, di  Rodolphe Lepigre, era di avere una sessione bash standard con una configurazione specifica via file definiti "missioni" che potevano essere "verificate" tramite i progressi nel gioco.

L'idea originale, di  Rodolphe Lepigre, era di avere una sessione da terminale, standard, con una configurazione specifica attraverso alcuni file definiti "missioni" che potevano essere "verificati" tramite i progressi nel gioco.

Cosa si intende per verificati?

2022-05-27 14:21 UTC, serhack commented on README-it.md
> +**Nota:** GameShell é attualmente sotto uno sviluppo pesante: la versione corrente non é stata testata dagli studenti. Non esitare a segnalare qualunque problema che potresti incontrare o suggeriment
GameShell è attualmente...

2022-05-27 14:21 UTC, serhack commented on README-it.md
> +Il primo commando scaricare l'ultima versione del gioco nella forma di un pacchetto che si auto estrarrá e il secondo commando avvierá e inizializzerá il gioco dall'archivio. Istrunzioni su come gioc
> commando

comando scarica l'ultima versione di Gameshell... 

> Istrunzioni

Istruzioni

2022-05-27 14:21 UTC, serhack commented on README-it.md
> +Il gioco NON verrá salvato quando esci e paramentri aggiuntivi sono necessari se vuoi eseguire X programmi da GameShell.  Approfondisci le differenze su [questa seaione](./doc/deps.md#running-GameShe
> seaione
sezione

2022-05-27 14:21 UTC, serhack commented on README-it.md
> +Licence
Forse è meglio tradurre anche questo? Oppure lasciare sia la versione in inglese che in italiano..

2022-05-27 14:21 UTC, serhack commented on i18n/start-help/it.txt
> +  -q      silenzioso:non mostra avvisi informativi
manca spazio tra : e non

2022-05-27 14:21 UTC, serhack commented on i18n/start-help/it.txt
> +          per un locale valido.
"per un locale valido": puoi migliorarlo?

2022-05-27 14:21 UTC, serhack commented on i18n/it.po
> +msgstr "Mentre stai aspettando, un sperente svicola via..."
> sperente

serpente

2022-05-27 14:21 UTC, serhack commented on i18n/it.po
> +msgstr "Mentre stai aspettando, una lumica va..."
> lumica
lumaca

2022-05-27 14:21 UTC, serhack commented on i18n/gameshell-welcome/it.txt
> +Utilizzare e amministrare un computer con un sistema Unix (o basato)
> (o basato)

(o basato su Unix)

2022-05-27 14:21 UTC, serhack commented on i18n/gameshell-welcome/it.txt
> +come (Linux, BSD o macOS) richiede l'utilizzo di una interfaccia
"...richiede l'utilizzo di un'interfaccia testuale..."

2022-05-27 14:34 UTC, Mte90 commented on README-it.md
> +Il primo commando scaricare l'ultima versione del gioco nella forma di un pacchetto che si auto estrarrá e il secondo commando avvierá e inizializzerá il gioco dall'archivio. Istrunzioni su come gioc
io che scrivo senza controllare...

2022-05-27 14:35 UTC, Mte90 commented on README-it.md
> +Licence
Ho lasciato la sezione licenza in inglese per evitare problemi

2022-05-27 14:36 UTC, Mte90 commented on i18n/start-help/it.txt
> +          per un locale valido.
`locale` é il termine tecnico e non é la lingua, potrei metterlo tra apici

2022-05-27 14:37 UTC, Mte90 commented on i18n/gameshell-welcome/it.txt
> +Utilizzare e amministrare un computer con un sistema Unix (o basato)
La versione originale é `Using and administering a computer running a Unix-like operating system (e.g., Linux, BSD or macOS)`

2022-05-27 14:45 UTC, serhack commented on i18n/gameshell-welcome/it.txt
> +Utilizzare e amministrare un computer con un sistema Unix (o basato)
"Utilizzare e amministrare un computer che esegue un sistema operativo basato su Unix (come ad esempio Linux, BSD o macOS).."

2022-05-27 18:42 UTC, rlepigre commented on missions/basic/01_cd_tower/i18n/it.po
> +msgstr "Devi cominciare dalla cima della torre."
I think this message should rather be translated into something like `"Devi ricominciare dall'inizio.", but I might be wrong since my Italian is very limited! :)

2022-05-28 15:52 UTC, serhack commented on i18n/it.po
> +msgstr "Congratulazioni, missione $MISSION_NB é stata completata con successo!"
Congratulazioni, **la** missione

2022-05-28 19:37 UTC, Mte90 commented on missions/basic/01_cd_tower/i18n/it.po
> +msgstr "Devi cominciare dalla cima della torre."
ho yes the translation isn't complete and also the revision :-)

2022-05-30 10:36 UTC, Anulo2 commented on README-it.md
> +* [Pierre Hyvernat](http://www.lama.univ-smb.fr/~hyvernat) (main developer,
Da cambiare in "sviluppatore principale" oppure è volutamente così?

2022-05-30 10:48 UTC, Mte90 commented on README-it.md
> +* [Pierre Hyvernat](http://www.lama.univ-smb.fr/~hyvernat) (main developer,
no mi é sfuggito 😂

2022-05-30 11:52 UTC, Anulo2 commented on README-it.md
> +* AA tutti gli studenti che hanno trovato *molti* bug nelle prime versioni.
Doppia A, typo

2022-05-30 11:53 UTC, Anulo2 commented on README-it.md
> +* Joan Stark (a.k.a, jgs), che ha disegnati centinaia di ASCII-art negli anni 90s. Molte delle ASCII-art in GameShell sono sue.
Che ha disegnato*, typo

2022-05-30 11:56 UTC, serhack commented on missions/basic/10_cp_standard_great_hall/goal/it.txt
> +del castello. Poiché rubandolili non passeresti inosservato, fai
* rubandoli

2022-05-30 11:57 UTC, serhack commented on missions/basic/10_cp_standard_great_hall/goal/it.txt
> +  Nota: ``cp`` é una abbreviazione di "copy".
è

2022-05-30 11:58 UTC, serhack commented on missions/basic/11_cp_wildcards_tapestries_great_hall/i18n/it.po
> +msgstr "Io voglio solo gli arazzi!"
Io voglio tutti gli arazzi/io volevo tutti gli arazzi!

2022-05-31 13:02 UTC, serhack commented on missions/basic/01_cd_tower/goal/it.txt
> +diversi. Verifica di stare nel perocrso corretto.
Sostituisci stare con "essere"

2022-05-31 19:57 UTC, serhack commented on missions/FINAL_MISSION/goal/it.txt
> +Il comando ``gsh index`` e ``gsh goto N`` sono particularmente
particolarmente

2022-05-31 19:59 UTC, serhack commented on missions/misc/03_tr_caesar_shift/secret_recipe/it.txt
> +Ricetta per la salsiccia al cioccolato
salsiccia al cioccolato? 😂 Salame al cioccolato

2022-05-31 19:59 UTC, serhack commented on missions/misc/03_tr_caesar_shift/secret_recipe/it.txt
> +Ricetta per la salsiccia al cioccolato
Riguardo la ricetta, non commento, non sono un cuoco haha

2022-05-31 20:02 UTC, serhack commented on missions/pipes_merchant_stall/01_pipe_1/i18n/it.po
> +msgid   ""
Traduzione mancante

2022-06-01 16:53 UTC, serhack commented on missions/permissions/02_chmod_r_file_king_quarter/goal/it.txt
> +Si dice che il Re tenga scritta la combinazione della sua cassaforte
"tenga scritta" non so, non mi suona bene. "Si dice che il Re abbia scritto", la comprensione è molto più semplice.

2022-06-03 07:59 UTC, phyver commented
Oops, I forgot to tell you about this "hidden" feature: text files that are displayed are formatted to the width of the terminal. Paragraphs are defined as in the "flowed" email format: consecutive lines with trailing white spaces are part of the same paragraph. (This is quickly described in `doc/mission.md`, section "Note on missions' `sh` files".)


So, we have (using `~` for trailing spaces)
`````
a paragraph with~
several~
consecutive lines~~
that end~
here

several independant
lines that do not
constitute a single
paragraph
`````

Try running GameShell in a very wide terminal to see what happens.

(That's not very important and I myself forget about it from time to time. The only consequence is that your text files will be displayed verbatim...)

2022-06-03 10:38 UTC, Mte90 commented
That's not a big problem (I noted the 80 char length) but I guess that we will do some tests when the localization is finished.

2022-06-07 07:27 UTC, Mte90 commented
Actual status in progress:

- permissions (assigned)
- pipe_intro_book_of_potions (assigned)
- processes (assigned)
- stdin_stdout_stderr

2022-06-09 10:23 UTC, Mte90 commented
I want to say thanks to @Anulo2 @wshield05 @maupao @ziriuz84 for the help with the localization that is now completed.

Now is time to review and everyone can do it from https://github.com/phyver/GameShell/pull/87/files clicking on the + blue button on the line with the issue, I will do the commits with the fixes to speed up (you can do a PR if you prefer).

So @serhack it's your time for a review but others can join :-D

2022-06-09 14:27 UTC, ciampix commented on i18n/gameshell-help/it.txt
> +  resetta la missione corrente
io metterei "reimposta la missione corrente"

2022-06-09 14:28 UTC, ciampix commented on i18n/gameshell-init-msg/it.txt
> +Puoi verificare se la missione é stata completata con
é l'accento è sbagliato...

2022-06-09 14:42 UTC, Mte90 commented on README-it.md
> +Siamo particolarmente interessati nel creare nuove missioni!
Si non sapevo come renderla in italiano, magari: `Siamo molto interessati nella creazione di nuove missioni!`

2022-06-09 15:36 UTC, ciampix commented on missions/pipes_merchant_stall/01_pipe_1/goal/it.txt
> +Puoi resettare il contatore con `gsh reset`, ma la stalla e i
personalmente viene un brivido quanto sento termini mezzi inglesi mezzi italiani come resettare... perché non reimpostare che è esattamente la traduzione di reset?

2022-06-09 15:38 UTC, ciampix commented on missions/pipes_merchant_stall/01_pipe_1/i18n/it.po
> +msgstr  ""
$MISSION_DIR/goal/it.txt

2022-06-09 15:38 UTC, ciampix commented on missions/pipes_merchant_stall/01_pipe_1/i18n/it.po
> +msgstr  ""
PAGATO

2022-06-09 19:48 UTC, avivace requested changes

2022-06-09 19:48 UTC, avivace commented on i18n/gameshell-HELP/it.txt
> +  resetta la missione attuale riavviando la shell
```suggestion
  ripristina la missione attuale riavviando la shell
```

2022-06-09 19:48 UTC, avivace commented on i18n/gameshell-HELP/it.txt
> +  resetta la missione attuale
```suggestion
  ripristina la missione attuale
```

2022-06-09 19:48 UTC, avivace commented on missions/basic/02_cd.._cellar/goal/it.txt
> +  Spostati alla cartella genitore (un passaggio indietro rispetto
```suggestion
  Spostati alla cartella genitore (un passo indietro rispetto
```

2022-06-09 19:48 UTC, avivace commented on missions/basic/02_cd.._cellar/goal/it.txt
> +  Vedi il percorso in cui ti trovi.
```suggestion
  Mostra il percorso in cui ti trovi.
```

2022-06-10 09:17 UTC, Mte90 commented
Uniformato il titolo delle missioni e sistemate altre cose.

2022-06-10 17:11 UTC, Mte90 commented on missions/pipe_intro_book_of_potions/05_pipe_head_tail/i18n/it.po
> +msgstr  "$GSH_HOME/Mountagna/Grotta"
questa è sfuggita

2022-06-10 17:12 UTC, Mte90 commented on missions/pipes_merchant_stall/00_shared/data/lastnames.it
> +the Bold
pure questi

2022-06-14 09:32 UTC, lmillucci commented on missions/stdin_stdout_stderr/05_stdout_stderr_redirection_merlin/i18n/it.po
> +msgstr  "Qual'è la chiave corretta?"
Si scrive [Qual è](https://www.treccani.it/enciclopedia/qual-e-o-qual-e_(La-grammatica-italiana)/) senza apostrofo :)

2022-06-15 10:36 UTC, Mte90 commented
Just a CTA to everyone in this ticket, If I don't get any other revision until friday I will mark the PR as ready.
So in the meantime just report on the various lines so I can do a single commit with all of them.

2022-06-16 13:26 UTC, Mte90 commented on missions/intermediate/03_tab_spider_lair/i18n/it.po
> +msgstr  "Perfetto, hai preso solo $nb_seconds secondi per completare questa missione!"
suona male visto che si parla di tempo

2022-06-16 13:27 UTC, Mte90 commented on missions/intermediate/04_bg_xeyes/i18n/it.po
> +        "Per la missione $MISSION_NAME è richiesto eseguire il server X."
forse anche qui si può migliorare

2022-06-16 13:28 UTC, Mte90 commented on missions/pipe_intro_book_of_potions/00_shared/i18n/it.po
> +msgstr  "tabella_dei_contenuti"
suona meglio indice

2022-06-16 14:43 UTC, ciampix commented on missions/intermediate/03_tab_spider_lair/i18n/it.po
> +msgstr  "Perfetto, hai preso solo $nb_seconds secondi per completare questa missione!"
Persino google translate lo traduce in: "Perfetto, ci sono voluti solo $nb_seconds secondi per completare questa missione!"

2022-06-16 14:44 UTC, ciampix commented on missions/intermediate/04_bg_xeyes/i18n/it.po
> +        "Per la missione $MISSION_NAME è richiesto eseguire il server X."
Per la missione $MISSION_NAME è richiesto un server X in esecuzione." "a running X server" è passivo...

2022-06-17 07:48 UTC, ziriuz84 commented on missions/pipe_intro_book_of_potions/00_shared/i18n/it.po
> +msgstr  "tabella_dei_contenuti"
Andando a ripescare la buona vecchia treccani direi che l'equivalente in inglese di "sommario" è più "excerpt" che "table of contents"

2022-06-17 07:49 UTC, ziriuz84 commented on missions/pipe_intro_book_of_potions/00_shared/i18n/it.po
> +msgstr  "tabella_dei_contenuti"
https://www.treccani.it/vocabolario/sommario2_%28Sinonimi-e-Contrari%29/

2022-06-17 08:10 UTC, avivace commented on missions/pipe_intro_book_of_potions/00_shared/i18n/it.po
> +msgstr  "tabella_dei_contenuti"
+1 per Indice

2022-06-17 09:01 UTC, Mte90 commented
I suggest a squash commit to have all the translation in a single commit instead all of this.

Thanks to all I think that I will write something in italian on forum.linux.it or my blog about this project once get approved :-)

2022-06-24 21:39 UTC, rlepigre approved these changes
Thanks for this amazing work! The PR looks good to me, but I don't speak enough Italian to comment on the phrasing, so I mostly payed attention to paths and a bit of formatting.

It would probably be a good idea to have someone test the game in Italian before we merge, it is possible there still are untranslated messages here and there.

2022-06-24 21:39 UTC, rlepigre commented on missions/basic/01_cd_tower/i18n/it.po
> +msgstr "$MISSION_DIR/treasure-msg/it.txt"
```suggestion
msgstr "$MISSION_DIR/goal/it.txt"
```

2022-06-24 21:39 UTC, rlepigre commented on missions/basic/01_cd_tower/i18n/it.po
> +msgstr "$MISSION_DIR/treasure-msg/it.txt"
```suggestion
msgstr "$MISSION_DIR/skip/it.txt"
```

2022-06-24 21:39 UTC, rlepigre commented on missions/basic/02_cd.._cellar/i18n/it.po
> +msgstr "$MISSION_DIR/skip/it.txt"
```suggestion
msgstr "$MISSION_DIR/treasure-msg/it.txt"
```

2022-06-24 21:39 UTC, rlepigre commented on missions/finding_files_maze/00_shared/i18n/it.po
> +msgstr  "GSH_HOME/Garden/Shed"
Maybe translate these paths?

2022-06-24 21:39 UTC, rlepigre commented on missions/finding_files_maze/03_find_1/i18n/it.po
> +msgstr  "gold_coin"
Maybe translate this?

2022-06-24 21:39 UTC, rlepigre commented on missions/pipe_intro_book_of_potions/00_shared/book_of_potions/it.txt
> +9. Pozione curativa omeopatica (parte 3) ----------- pagina 11
```suggestion
7. Pozione curativa omeopatica (parte 1) --------- pagine 8-9
8. Pozione curativa omeopatica (parte 2) ---------- pagina 10
9. Pozione curativa omeopatica (parte 3) ---------- pagina 11
```

2022-06-24 21:39 UTC, rlepigre commented on missions/pipe_intro_book_of_potions/00_shared/book_of_potions/it.txt
> +== pagina 2 -===============================================================
```suggestion
== pagina 2 =================================================
```

2022-06-24 21:39 UTC, rlepigre commented on missions/pipes_merchant_stall/00_shared/data/firstnames.it
> +Nicolo’
```suggestion
Nicolò
```
Not sure about this.

2022-06-25 07:05 UTC, phyver commented
Sorry, busy days...

I'm very happy this reached completion!

I'll try playing a game in Italian in the next few days, but I doubt I'll find more than Rodolphe, and I don't speak Italian.

Squashing this PR into a single commit might be good, but I don't know how git/github deals with contributors when you do that. Does it keep a list of individual contributors?

Also, don't forget to add your names (real names, github names, LUG name, or whatever) to the various `README` files.

2022-06-27 11:06 UTC, Mte90 commented
Thanks for this review... I missed that lines.

I tested in Italian days ago and was working but I didn't tested all the missions.
My guess is that only after is merged we will get more players also in Italian that can do some real playing.

2022-06-27 19:02 UTC, rlepigre commented
@phyver I think in this case, since there are quite a few contributors, it is actually better to not squash, and the commits to the main branch with a merge commit. Otherwise, it might be hard to attribute credit where it is due.

@Mte90 it'd be great if you could edit the `README.md` and `README-it.md` files to add your names to the list of contributors. It might be best to add a section (e.g., after the "Mission contributors") with something like:
```
### Translation

#### Italian version

* Daniele Scasciafratte (@Mte90)
* ...
```
Including the names (or at least GitHub handle) of everyone that contributed to this MR.

After this, I think we are good for merging.

2022-06-28 07:46 UTC, Mte90 commented
I added their names but I am missing @serhack, @michirod and @wshield05 (if want their real names in the list or I can put just the nicknames)

2022-07-03 09:55 UTC, gioisco commented
I tried to start the game on Fedora 35 and I receive this message error when I execute `start.sh`
```
  ____                      ____  _          _ _
 / ___| __ _ _ __ ___   ___/ ___|| |__   ___| | |
| |  _ / _` | '_ ` _ \ / _ \___ \| '_ \ / _ \ | |
| |_| | (_| | | | | | |  __/___) | | | |  __/ | |
 \____|\__,_|_| |_| |_|\___|____/|_| |_|\___|_|_|

                             _
                           _/ \
          _               /    \
         / \_   __       /\/\  /\
        /    \ /  \     /    \/  \
       /\/\  /\    `--./.'-    `-.\
      /    \/  ' ^ _    _  _
    /\ ____..      YY  Y     _   |~  _
   /._/  _ \_        Y  Y   [_]--'--[_]
  / / .'/#\_ `-.    Y  YY   |'|""`""|'|
    .-_/#@##\  `\"" ' Y     | | /^\ | |
   " "'"''"/home/giovanni/Games/GameShell/missions/finding_files_maze/04_find_2/i18n/it.po:28:32: invalid control sequence
/home/giovanni/Games/GameShell/missions/finding_files_maze/04_find_2/i18n/it.po:28:77: invalid control sequence
/home/giovanni/Games/GameShell/missions/finding_files_maze/04_find_2/i18n/it.po:28:91: invalid control sequence
msgfmt: found 3 fatal errors
'"'''" '         |_|_|I|_|_|

Press Enter to continue.
```

I'm executing the game from the branch `italian` from the repository of @Mte90

2022-07-03 17:20 UTC, gioisco commented
Mismatch in mission 15.
In the file `missions/misc/02_nano_journal/goal/it.txt`
```
Crea un file chiamato "storico.txt" nella tua cassa e scrivici
un breve messaggio.
```
but in `missions/misc/02_nano_journal/i18n/it.po` the real name required is `"registro.txt"`, not `"storico.txt"`
```
msgid "journal"
msgstr "registro"
```

2022-07-03 17:23 UTC, serhack commented
> I added their names but I am missing @serhack, @michirod and @wshield05 (if want their real names in the list or I can put just the nicknames)

Just leave my nick :) Thanks for your work!

2022-07-03 17:34 UTC, gioisco commented
Mismatch in mission 16.
In `missions/intermediate/02_alias_journal/goal/it.txt`
```
Creare un alias "journal" in modo da editare il tuo file storico
ovunque tu sia.
```
but in `missions/intermediate/02_alias_journal/i18n/it.po`
```
msgid "journal"
msgstr "storico"
```
is expected alias named `storico` to complete the mission and not named `journal` as it is written in the goal.

2022-07-03 18:30 UTC, gioisco commented
In the file `missions/intermediate/02_alias_journal/gshrc/it.sh` a translation is missing
#### Current file
```
# Questo file è caricato (o    in shell jargon) quando il gioco
# si avvia. Puoi usarlo per registrare alias (e altre cose)
```
#### My proposal
```
# Questo file è caricato (o "sourced" in gergo shell) quando il gioco
# si avvia. Puoi usarlo per registrare alias (e altre cose)
```

2022-07-03 18:47 UTC, gioisco commented
Mismatch in mission 19.
In the file `missions/finding_files_maze/01_ls_cd/goal/it.txt`
```
Trova la moneta di bronzo
```

In the `missions/finding_files_maze/01_ls_cd/i18n/it.po`
```
msgid "copper_coin"
msgstr "moneta_di_rame"
```

2022-07-03 19:14 UTC, gioisco commented
Bug of line break in mission 22.
The goal is viewed like this
```

  .-------------------------------------------------------------------------------------------.
 /  .-.                                                                                   .-.  \
|  /   \                                                                                 /   \  |
                                                         |    /| |
                                                       |\  | |/|
                                                                           | `---' |
      |       |anziano eremita smemorato di nome Servillus si è accampato in una 
                    |       | vecchio libro delle pozioni di cuoio.
      |       | nella grotta e aiutalo a ricordarsi la ricetta del suo famoso tè 
[...]
```

As you can see the file `missions/pipe_intro_book_of_potions/01_head/goal/it.txt` has different line terminator
```
[giovanni@giovanni GameShell]$ file missions/pipe_intro_book_of_potions/01_head/goal/*
missions/pipe_intro_book_of_potions/01_head/goal/en.txt: ASCII text
missions/pipe_intro_book_of_potions/01_head/goal/fr.txt: Apache Avro version 101
missions/pipe_intro_book_of_potions/01_head/goal/it.txt: Unicode text, UTF-8 text, with CRLF line terminators
```

## How I fix
1) Open with **vim** `missions/pipe_intro_book_of_potions/01_head/goal/it.txt`
2) :set fileformat=unix
3) :wq
4) Fixed :)
```
  ,-------------------------------------------------------------------------------------------------------------------------------.
 (_\                                                                                                                               \
    |  Obiettivi missione                                                                                                           |
    |  ====================                                                                                                         |
    |                                                                                                                               |
    |  Un anziano eremita smemorato di nome Servillus si è accampato in una grotta con il suo vecchio libro delle pozioni di cuoio. |
    |  Vai nella grotta e aiutalo a ricordarsi la ricetta del suo famoso tè alle erbe.  
```

2022-07-03 19:55 UTC, gioisco commented
Bug in mission 22.
I don't know when the path `$GSH_HOME/Montagna/` was created.
Anyway, the files
`missions/pipe_intro_book_of_potions/01_head/i18n/it.po` 
`missions/pipe_intro_book_of_potions/02_tail/i18n/it.po`
`missions/pipe_intro_book_of_potions/03_cat/i18n/it.po`
have a translation mistake
```
msgid   "$GSH_HOME/Mountain/Cave"
msgstr  "$GSH_HOME/Mountagna/Grotta"
```
and some of they have CRLF line terminator.
```
[giovanni@giovanni GameShell]$ file missions/pipe_intro_book_of_potions/*/i18n/it.po
missions/pipe_intro_book_of_potions/00_shared/i18n/it.po:         GNU gettext message catalogue, Unicode text, UTF-8 text, with CRLF line terminators
missions/pipe_intro_book_of_potions/01_head/i18n/it.po:           GNU gettext message catalogue, ASCII text, with CRLF line terminators
missions/pipe_intro_book_of_potions/02_tail/i18n/it.po:           GNU gettext message catalogue, ASCII text, with CRLF line terminators
missions/pipe_intro_book_of_potions/03_cat/i18n/it.po:            GNU gettext message catalogue, ASCII text
missions/pipe_intro_book_of_potions/04_pipe/i18n/it.po:           GNU gettext message catalogue, ASCII text, with CRLF line terminators
missions/pipe_intro_book_of_potions/05_pipe_head_tail/i18n/it.po: GNU gettext message catalogue, Unicode text, UTF-8 text, with CRLF line terminators
```

2022-07-04 08:21 UTC, Mte90 commented
Fixed all the issue reported (about crlf there is the command `dos2unix` that does automatically).

Anyway instead to do multiple comments you can use the Files view of the pull requests and report the error in that line so there are less notifications.

2022-07-11 15:31 UTC, Mte90 commented
Tested with the latest changes and now the tests are working!

2022-07-11 15:55 UTC, phyver commented
In file `i18n/gameshell-HELP`, I removed (48e7592f) a reference to `start.sh` in command `gsh exit`.
It now reads
`````
gsh exit
  quit (and save) the current game
`````

I just added (7860604f) an option `-G` to GameShell described in file `i18n/start-help/en.txt`
`````
  -G      do not use gettext for translation (everything will be in English)
  -L ...
`````

It might be worth checking if some other `en.txt` / `*.po` files have been modified since the beginning of this PR so that one of you can update the translations.

2022-07-11 16:15 UTC, phyver commented
Oops, some commits weren't meant for this branch!
I'll fix this when merging the PR.

I cannot comment on the Italian parts, but the rest looks good.
So, someone should commit a translation for the `gameshell-HELP` and `start-help` Italian files, possibly check for other file to update. I guess it wouldn't hurt to have an outsider make a full run of GameShell in Italian.

I'll probably have to do some rebasing to remove the duplicate commits I made today, but I'll keep all the commit history.

2022-07-11 17:20 UTC, Mte90 commented
Checked that files and others and I didn't saw other changes.

2022-07-12 14:28 UTC, phyver commented
Any pending commit?
Or plans for some work on this branch?

If not, I can try merging later this week.

2022-07-12 14:45 UTC, Mte90 commented
It is ready for me :-)

2022-07-13 11:01 UTC, phyver commented
merged into `master`!
Congratulations to everyone and thanks for the amazing work!

2022-07-13 11:03 UTC, Mte90 commented
So this pr can be closed.

2022-07-13 11:03 UTC, closed without merging

2022-07-13 11:58 UTC, phyver commented
Ah, yes.
Github didn't realize the PR was merged, probably because I had to do some rebasing.